name: dariaskripka
favicon: null
layout_spectrum: 0.9975
typography_spectrum: 0.4765216112136841
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a5a5a5'
    - '#020202'
    - '#282828'
    - '#efefef'
    - '#6d6d6d'
  brandStrength: 0.6517447722144425
  lightness: 0.8842708102893084
  saturation: 0.424684896832332
  rhythmicContrast: 0.27086558449082077
purpose: []
